version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17.5-browsers
    steps:
      - checkout
      # getsubmodules
      - run:
          name: "pull-submodules"
          command: |
            git submodule update --init --recursive
      # Installing ionic cli
      - run:
          name: install-angular/cli
          command: 'sudo yarn global add @angular/cli'
          when: always
      # Creating result folder
      - run:
          name: create-result-folder
          command: 'mkdir result'
          when: always
      - run:
          name: prepare-ang
          command: 'cd ./projects/c8osdkangular && ([ -f ./yarn.lock ] && rm yarn.lock || echo "No yarn.lock file found") && ([ -d ./node_modules ] && rm -rf ./node_modules || echo "No node_modules directory found")'
          when: always
      # Installing dependencies
      - run:
          name: install-dep-ang
          command: 'yarn install && cd ./projects/c8osdkangular && yarn install  && cd ./src/c8osdk-js-core && yarn install'
          when: always
      # TESTANGULAR
      - run:
          name: test-ang
          command: 'cd ./projects/c8osdkangular && ng test c8osdkangular --watch=false 2>&1 | tee -a ../../result/angular8.txt'
          when: always
      # Check for results
      - run:
          name: eval-ang
          command: '(grep -qs "TOTAL: [0-9]* SUCCESS" in ./result/angular8.txt && cp ./.circleci/results/icons/passed.png ./result/angular8.png || cp ./.circleci/results/icons/failed.png ./result/angular8.png)'
          when: always
      - store_artifacts:
          path: ./result/